### ISSUE TITLE
What Went Wrong

### ISSUE THREAD

**Issue by irfaan96** [2100711/ICT2106_P1-6#39]
Reviewing D1 report and identifying the mistakes made.

**Comment by hengwej** [comment]
Firstly, we should have started to do the D1 report earlier so that we do not have to rush and can have more time to check through before submission. Secondly, more communication is needed within the team, the module and the lab. This would enable everyone to be clear about what is going on and to make sure that everyone is on the same page. Lastly, we should have been better prepared for the client presentation showing the features we have. We should have prepared something whether display visuals or code to show that the feature is there but not completed yet.

**Comment by loopedfrog4** [comment]
For our D1 retrospection, I realised that having we have missed out on having a sequence diagram in our D1 submission.

**Comment by catifier** [comment]
For our D1, we made a huge mistake on the Class Diagram, while missing out on other diagrams such as the Sequence Diagram. Our client presentation was not well prepared and the client likely could see it.

**Comment by jibai-kia** [comment]
There was a lack of communication at the module and lab level, which impacted our team's preparation for client meetings and report submission. To improve, we should have started the D1 report earlier and communicated more effectively within the team, module, and lab. During client presentations, we should have provided visual representations of incomplete features to aid client understanding. We missed including a crucial sequence diagram in our D1 submission, leading to misunderstandings in the project's different layers. Our client presentation was not well-prepared, and miscommunication with other module teams led to errors in the class and component diagrams.
