### ISSUE TITLE
Actions To Take

### ISSUE THREAD

**Issue by irfaan96** [2100711/ICT2106_P1-6#40]
Identifying the necessary changes to be made based on the feedbacks given.

**Comment by irfaan96** [comment]
Based on your D1 feedback and also the general feedback from the profs we would like to establish communication for module and lab level. We would also like to start doing the D2 report and code our project side by side to not miss any relevant information. Consistently update the GitHub project board rather than doing it last min.

**Comment by hengwej** [comment]
The improvements to be made is that we should update the GitHub project board frequently so that everyone can see each other's progress and know what is going on.  We should also have more communication within the module and lab and be more prepared for client presentation. We need to also start the D2 report earlier so that we can have more time to fill up and check through to ensure that we do not miss out anything important.

**Comment by jibai-kia** [comment]
After receiving feedback from D1 and the professors, our team plans to improve communication at the module and lab level. We will start working on the D2 report and code the project simultaneously to avoid missing relevant information. To improve, we will update the GitHub project board frequently for better transparency and communication among team members. We will also communicate more effectively within the module and lab and be better prepared for client presentations. Starting the D2 report earlier will give us more time to fill up and check for important information. As a result of the feedback, our team is now making efforts to communicate with each other and complete our work efficiently.
